### ISSUE TITLE
Values missing for enumeration of 'CLPHazardClassCategory'

### ISSUE THREAD

**Issue by mm-basf-bs** [esdscom/sdscom-xml#110]
Within section 2 and 3 of the SDS BASF refers to a list of 105 possible values for ‘CLP Hazard Classification and Category’.
Some of this values are not yet defined as enumeration value for ‘CLPHazardClassCategory’ in SDScom.
May it be possible to add the 'missing' values to the enumeration for ‘CLPHazardClassCategory’ in SDScom?
The values used by BASF and needed in SDScom are:

Eye Dam./Irrit. 1
Eye Dam./Irrit. 2
Flam. Aerosol 1
Flam. Aerosol 2
Ox. Gas 1
Skin Corr./Irrit. 1A
Skin Corr./Irrit. 1B
Skin Corr./Irrit. 1C
Skin Corr./Irrit. 2

**Comment by dirk-qualisys** [comment]
SDScom must implement exactly the hazard classes and categories as described in CLP annex VI, section 1.1.2.1.1. From your list, I can see the following reasons:

- "Eye Dam./Irrit." and "Skin Corr./Irrit." are no proper hazard classes. Eye Dam. 1 and Eye Irrit. 2 exist, but not vice versa. The same is true for skin.
- "Flam. Aerosol" was replaced by "Aerosol" in ATP 4. Since its transition period passed, there is no need to communicate the old classification as the respective SDSs must receive a revision.
- "Ox. Gas 1" indeed uses a wrong abbreviation in HazardClassCategoryEnum, thus I classify this issue as a bug. Thank you for bringin this to our attention!

**Comment by dirk-qualisys** [comment]
For the other classes/categories in your list, you might want to use a mapping to the annex VI terms.

**Comment by Henrich-BGRCI** [comment]
In respect to 8. ATP, it should be also added Skin Corr. 1 in addtition to Skin Corr. 1A, Skin Corr. 1B, and Skin Corr. 1C.

**Comment by dirk-qualisys** [comment]
Thank you for this hint. I added "Skin Corr. 1" in accordance with GHS rev. 6, adopted by the 8th ATP.
