### ISSUE TITLE
More than one CAS-number / EC-number per substance within section 3

### ISSUE THREAD

**Issue by mm-basf-bs** [esdscom/sdscom-xml#111]
Within section 3 of the SDS in rare cases it may appear that BASF uses substances with more than one CAS-number or EC-number assigned.
(also see example of SDS section 3 attached)
![example_section_3](https://cloud.githubusercontent.com/assets/20518635/21392591/e144d55a-c790-11e6-9039-df3efff609c5.JPG)

Actually not more than one CAS-number and one EC-number can be assigned to one substance in SDScom.
Would it be possible to extend this in SDScom to have more than one CAS-no. or EC-no. at one substance?

**Comment by Henrich-BGRCI** [comment]
Is there any reason, why you use for the mixture MCI/MI the individual CAS and EC numbers and not that one given for the mixture?
In the CL Inventory, the mixture MCI/MI (3:1) is already given with EC 611-341-5, CAS 55965-84-9 and Index 613-167-00-5; therefore, one CAS, EC and Index, each, should be sufficient.

**Comment by dirk-qualisys** [comment]
I agree that one CAS / EC number should be sufficient. Mixtures like "MCI/MI 3:1" can be listed as two substances, certainly with two separate classifications (and SCLs if appropriate). You might then calculate SCLs for your product based on the SCLs for the MCI/MI mixture.

What happens in the SDS cited above is that the table in fact lists a two-level recipe hierarchy which IMHO is not the goal of REACH. Hints that may support this:

- Annex II 0.2.3: "The information in the safety data sheet shall be written in a clear and concise manner."
- Annex II 3.2: "The product identifier, the concentration or concentration ranges and the classifications shall be provided for at least all substances referred to in points 3.2.1 or 3.2.2." - read: break intermediates down to their ingredient substances.

**Comment by mm-basf-bs** [comment]
Many thanks for your hints. Creating this issue was made from a technical point of view. As this now seems to be more a problem of data content, I forwarded your hints to the product safety department of our customer and wait for further response.

**Comment by mm-basf-bs** [comment]
Referring to your hints upon example "MCI/MI (3:1)" the product safety department of our customer agreed that this has to be fixed by proper maintenance of the underlying substance data.
Nevertheless they mentioned another example where it might be necessary to state 2 CAS numbers at one component at SDS section 3, especially as this component has 2 CAS numbers assigned within its official ECHA dossier (also see example below).
![example_silicon_dioxide_dossier](https://cloud.githubusercontent.com/assets/20518635/22250177/4ac439b0-e246-11e6-8c69-7302f6b45c37.JPG)

**Comment by dirk-qualisys** [comment]
There are quite many substances that have more than one CAS, and only sometimes for good reasons I talked to one internal and one external expert about this. These are the more common CAS numbers for SiO2:

7631-86-9 Silica
14464-46-1 Cristobalite (SiO2)
14808-60-7 Quartz (SiO2)
112945-52-5 Silicon dioxide, chemically prepared

They are different e.g. regarding particle size and thus effect on lungs. CAS #112926-00-8 is less common. Up to this point, we are discussing just the chemical part and I would recommend to decide for just one of the CAS# for the sake of clarity. 

On the other hand, substance registrations with EChA list exactly the two(!) CAS numbers that you mention (while the load of different classifications clearly show that this registrations covers different particle sizes). This is more a compliance issue - is it required to match the registration identification fully, or is it preferrable to be more specific and link to the registration just with the REACH registration number? I will approach two legal experts with this.

**Comment by dirk-qualisys** [comment]
There is feedback already - and this topic has different aspects:

1. Pure substances such as SiO2: While there is quite some bad data in the supply chain, the rule still is one substance - one CAS, i.e. the CAS database always has a leading CAS number that should be used in the SDS. The reason for having several CAS in one registration as published on the EChA web site is that EChA may combine several registrations into one dataset if they think there is a match. Nevertheless, the SDS author must provide the leading CAS (only) for every substance.

2. Some groups (of hydrocarbons, isocyanates, or tensides) only have a group CAS number. Due to different properties and hazards, there are more than one registration for each group. In this case, it is correct to mention no CAS number in section 3 because the registration does not match the whole group that is covered under the CAS. **_But..._** for legal regions outside the EU, it does make sense to mention the group CAS so that e.g. listings in chemical inventories can be checked. 

It should be considered to add an "alternative" or "group CAS" for consistent hazmat management worldwide. Further investigation is necessary to determine whether a) there is more than one alternative/group CAS necessary, b) the concept of binding the alternative CAS to regions holds true. Thus I label this as an enhancement for version 5, where a scope beyond the EU will be discussed.

**Comment by Leo3E** [comment]
Proper maintenance of the underlying substance data on both sides, as mentioned in postings above, is really a key.  XML exchange of data can't be an alternative to it as it can't accommodate for all complexities of substance / regulatory data.  Some examples of such complexities are described above.

On groups, below are a few examples for your consideration.

CAS RN: 100-00-5 Name: 1-Chloro-4-nitrobenzene is heavily regulated globally.  It's also a member of a regulated group for Nitro and chloronitro derivatives of benzene hydrocarbons, that, for example, is regulated in France - Table of work-related illnesses (Les Maladies Professionnelles), as amended through Decree No. 2014-605 of 6 June 2014 (JORF no.132, 8 June 2014).  In this scenario, there's no CAS for a group, so nothing can be specified in the Group CAS.  

The same CAS can be a member of more than one regulatory group.  For example, outside of EU, a group Preparations containing substances 1 through 36 according to the Japanese ISHL Class 2 Designated Chemical Substances List, will include 100-00-5 and be regulated by Japan. Specified Chemical Substances for Health Damage Prevention (ISHL Order App. 3; Rule of Health Damage Prevention, Art. 2 and by Appendices 1 and 2, as amended through September 17, 2015) and by Japan. ISHL Class 2 Designated Chemical Substances (ISHL Enforcement Order, Table 3; MOL Ordinance No. 39, Table 1, as amended through September 17, 2015).

This example is not quite what Dirk mentioned above since I used a chemical with a CAS number; however, it shows that the same chemical can be a member of several groups for regulatory purposes.

It also shows that the regulatory grouping concept is more driven by structure and not by the region.  

Thus, on (a) in the previous posting, several groups are possible, but those groups may or may not even have CAS numbers.  The analysis of chemical groups / regulations should be done while generating SDS on the sending side, so I'm not sure that Group CAS numbers (or other group IDs) need to be communicated in XML as some of them may be specific to regulatory content providers. 

On (b), probably not.

**Comment by dirk-qualisys** [comment]
I take this as a vote from Leo that we should not have more than one CAS for the EU, which I agree with and which is supported by a EuPhraC workgroup member I consulted. So let's document that the author of a SDS needs to apply his/her expertise to choose the best and most specific CAS RN.

Regarding other legal areas, I do think that the same is true: There is one "best" CAS per legal area. Which in turn means that if different CAS RNs are used to meet local registration/notification requirements, we should indeed be able to have one CAS per region, or maintain multiple CASs and assign a list of regions to each (while ensuring that each region is only part of the list for one CAS). Correct me if I am wrong.

**Comment by Henrich-BGRCI** [comment]
According to the answer of the reach-clp-biozid Helpdesk, where I asked this question regarding giving several CAS numbers, SDScom should allow several CAS numbers. because it is allowed to make a group SDS. The Group SDS could cover different substances which are similar according the health and safety-related properties. In this case, for each of the substances the CAS number should be listed.

**Comment by Henrich-BGRCI** [comment]
According to the discussion above, a single CAS number for a substance seems to be enough (in complexType Substance for CasNo a maxOccurs of 1). But how can be built a group SDS giving a set of substances or mixtures? This question is related to #95 .

**Comment by dirk-qualisys** [comment]
As part of the question are different CAS numbers for different regions, I would like to solve this for version 5.0 which covers multiple regions. Those regions will have different ingredient lists, and each one can carry one CAS number per ingredient, so this is solved. The only constraint is that the exporting system must assign CAS numbers to regions, or otherwise decide which one of the list of CAS RNs should become part of the ingredient list.

For group SDSs for substances, I believe multiple CAS RNs are not sufficient. REACH Annex II: "A single safety data sheet may be provided to cover more than one substance or mixture where the information in that safety data sheet fulfils the requirements of this Annex for each of those substances or
mixtures." This means that all identifiers must be provided for each substance, especially including the substance name and (in the EU) its registration number. This is currently provided only for ingredients in section 3, but not for a substance in section 1, and more identifiers are missing. Thus I will open a separate issue for this which also covers the case of multiple substances in section 1.

Can we close this issue under these circumstances?
