### ISSUE TITLE
SafetySignEnum

### ISSUE THREAD

**Issue by joern-pes** [esdscom/sdscom-xml#113]
There is the possibility to export the Safety Signs which displayed in section 8 as an Object named SafetySign. Therefor it is mandatory to use a PhraseCode of type SafetySignEnum. But I'm not sure about the mapping of this enumeration because it can suppose 12 different values from 1.1 to 3.2. This is not consistent with the number or the numbering of the order or prohibition symbols. Can someone explain the use of this enumeration because there is no explanation in the documents available to me?

**Comment by nils-eska** [comment]
This enumeration was introduced by the Norwegian working group with the following values
1.1: No smoking
1.2: Smoking and open fire prohibited
1.3: Do not extinguish with water
1.4: Do not touch
2.1: Eye protection
2.2: Respiratory protection
2.3: Foot protection
2.4: Hand protection
2.5: Protective suit
2.6: Face protection
3.1: Emergency shower
3.2: Eye wash equipment
From my point of view, these values should not be part of the sds but this was a concession to the Norwegian working group.
I would suggest to change this value back to "Phrase" or to revise the enumeration considering ISO 7010.
Maybe Torstein from EcoOnline can provide more details concerning this issue.

**Comment by joern-pes** [comment]
I would support the suggestion to change the value to an enumaration based on ISO 7010. The current object isn't useful for us.

**Comment by dirk-qualisys** [comment]
I introduced a matching data type RmmPictogramEnum today for SUMIs (see #101). Please check if this meets your expectations.

**Comment by dirk-qualisys** [comment]
EN ISO 7010 is meant to harmonise these signs internationally and younger than the original SDScom specification I think, so a replacement should be ok.

**Comment by dirk-qualisys** [comment]
Here is my understanding of matching the current implementation to ISO 7010:
1.1: No smoking = P002
1.2: Smoking and open fire prohibited = P003
1.3: Do not extinguish with water = P011
1.4: Do not touch = P010
2.1: Eye protection = M004
2.2: Respiratory protection = M017
2.3: Foot protection = M008
2.4: Hand protection = M009
2.5: Protective suit = M010
2.6: Face protection = M013
3.1: Emergency shower = E012
3.2: Eye wash equipment = E011

Only Mxxx fit in the position of PersonalProtectionEquipment/SafetySigns because Exxx describe technical measures and Pxxx describe organizational measures. Thus I split the former content into three fields in the appropriate places.
