### ISSUE TITLE
Add SCL info to type Classification

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#120]
See CLP annex VI: SCL information consists of a list of decreasing percentages and the according hazard category.

Bear in mind that Eye Dam. 1 overrides Skin Corr., so the SCL of Eye Dam. 1 may result not only in Eye Irrit. 2, but aditionally in Skin Irrit.! How can we handle this? Allow for more than one classification per SCL percentage? Or introduce a "hidden" Skin Corr. classification which carries the SCL?

**Comment by Suter-IK** [comment]
Do you have an example for this?

**Comment by dirk-qualisys** [comment]
Yes of course, the easiest being Formaldeyde's (CAS 50-00-0) harmonised classification as listed in regulation (EU) Nr. 605/2014:

**Pure substance:** 
Carc. 1B; H350
Muta. 2; H341
Acute Tox. 3; H301*
Acute Tox. 3; H311*
Acute Tox. 3; H331*
Skin Corr. 1B; H314
Skin Sens. 1; H317

**SCLs:**
Skin Corr. 1B; H314: C ≥ 25 %
Skin Irrit. 2; H315: 5 % ≤ C < 25 %
Eye Irrit. 2; H319: 5 % ≤ C < 25 %
STOT SE 3; H335: C ≥ 5 %
Skin Sens. 1; H317: C ≥ 0,2 %

Note that Eye Irrit. and STOT SE do not appear in the pure substance classification.

**Comment by Henrich-BGRCI** [comment]
Is there already any solution to transfer the SCLs related to a classification?

My aim is to "misuse" SDScom to provide the GisChem datasheets in machine readable form (not as a real SDS, but as a pseudo SDS). In many datasheets (e.g., Formaldehyd http://gischem.de/suche/dokument.htm?client_session_Dokument=2302), we give SCLs for different classifications. 
If there is no specific field for the SCLs, would it be the best place to write it in ClpClassificationComments or ClpClassificationNotes (why maxOccurs="4"?) of DT Classification?

**Comment by Henrich-BGRCI** [comment]
In the draft for the new ECHA SDS guidance document it is stated for the substances indicated in subsection 3.2.: "the specific concentration limit, the M-factor and the acute toxicity estimate for the substance in Part 3 of Annex VI to Regulation (EC) No 1272/2008 or as determined in accordance with Annex I to that Regulation shall be indicated, if available."

Even the regulation has not passed yet, I think new fields for SCL and ATE of Annex VI should be added to ClpHazardClassification. My Suggestion is to add the following elements to ClpHazardClassification (before MultiplyingFactor):

`<element name="SpecificConcentrationLimit" minOccurs="0" maxOccurs="1" type="PercentageValue"/>`

`<element name="AcuteToxicityEstimate" minOccurs="0" maxOccurs="unbound" type="AcuteToxicityEstimateValue"/>`
`<complexType name="AcuteToxicityEstimateValue"><sequence>
<element name="UnitValue" type="UnitValue" minOccure="1" maxOccure="1">
<element name="PhysChemUnitValue" type="PhysChemUnitValue" minOccure="1" maxOccure="1"></sequence></complexType>`

**Comment by dirk-qualisys** [comment]
Up until today, I could not figure out a stringent and easy enough model that would enforce the logic, i.e. that would allow schema validation to sort out SCLs that cannot be derived from one of the pure product classifications. So this needs to be handled with application logic, like other aspects of classification validation. This leaves two options for SCLs:

1. Create one common list of classifications (for both the pure substance and the SCLs) including min/max percentages. While the minimum percentage is always >=, the maximum percentage could be < or <=, depending on the applicability for the pure product.
2. Create two lists, one for the pure product without percentages, and one for SCLs with min (>=) and max (< only) percentages.

Option 2 has redundancy in case of classifications valid for <= 100% (i.e. the pure product and a dilution, as for "Skin Corr. 1B" in the example above). But it has the beauty of listing product classifications separately, which helps with applications that to not use SCLs, and presenting SCLs in the same manner that ATPs show it in the tables. Thus I propose to add a node "SpecificConcLimits" to each of the Classification nodes for Atp08 and Atp12 (and others in future).

**Comment by dirk-qualisys** [comment]
SCLs also apply to EUH0xx phrases (N.B.: which would in fact qualify as classifications anyway)! Example: Index no. 017-011-00-1, APT 13.

**Comment by dirk-qualisys** [comment]
ATEs apply to Acute Tox. classifications only, just as M factors apply to Aquatic Tox. classifications only. I think Index no.  603-180-00-4 as of ATP13 delivers the most complex example:

Inhalation: ATE = 0,05 mg/L (dust or mist)
Dermal: ATE = 50 mg/kg BW
Oral: ATE = 35 mg/kg BW

Thus, no quantifier, but a value, a unit, and possibly a remark (dust or mist) which is no part of the unit.

One could dispute if we should add ATE and M-factor to the classification type, or list three ATEs and two M factors separately (because these are all that are possible). I will be consistent with the current M-factor implementation and add one ATE to the classification node, which can have multiple instances.

ATEs only apply to ATP13, ATP12 and newer, thus will not be implemented for AtTP08 classifications.

**Comment by Henrich-BGRCI** [comment]
Sorry, there was a mistake in the suggested code for AcuteToxicityEstimate: Instead of using the element PhysChemUnitValue, the two elements ExposureRouteEnum and UnitValue should be sufficient to describe ATE. UnitValue with n=1 is sufficient because it allows both, an upper and a lower value.

I agree, it can be discussed to handle SCL, ATE and M-factor as the same element. For the sake of simplicity and because M-factor is already implemented in vers. 4.4.0.2, I would prefer three distinct elements as leaves of ClpHazardClassification: SpecificConcentrationLimit (n=0..1), AcuteToxicityEstimate (n=0..3) and MultiplyingFactor (n=0..1). Two MultiplyingFactors are not needed, because one belongs to Aquatic Acute and the other one to Aquatic Chronic. For SpecificConcentrationLimit it is the same, because one SCL is belonging exactly to one Hazard Class Category.

For distinguishing between SCL of substance or mixture, SCL of a pure substance are written in HazardIdentification/Classification/ClpClassification/ClpHazardClassification, and SCL of components of a mixture in Composition/Component/Classification/ClpHazardClassification. 

For covering SCL of EUH statements of substances, the element HazardIdentification/HazardLabelling/ClpLabellingInfo/ClpSupplementalHazardInformation could be extended by the element SpecificConcentrationLimit, too.

I don’t see the need of validation of SCL, ATE and M-factor against different ATP. We do not have such a validation against an external list (here: Annex VI). Even an internal validation across different elements is not given. In my opinion, the exporting system is responsible for filling correct data.

**Comment by dirk-qualisys** [comment]
SCL implementation in Iuclid's FEXIBLE_RECORD-Ghs-5.0 format used for PCN: 
![grafik](https://user-images.githubusercontent.com/4411785/90988361-7c342700-e592-11ea-9d61-947a059fff4b.png)
and the corresponding M-factor implementation:
![grafik](https://user-images.githubusercontent.com/4411785/90988407-cfa67500-e592-11ea-9264-fe7a6e2e0ebb.png)
I could not find any changes to this, or an ATE implementation, in the Iuclid 6.5 draft of April 2020 (the newest I could find published).
For better compatibility with Iuclid data representation, I suggest changing the current implementation to create three ATE fields and two MFactor fields instead, on the same level as SpecificConcLimits. This is similar to Mr. Henrich's suggestion. For SCLs, the Iuclid implementation and ours is similar already and there can be more than one SCL to the same hazard class, so the current implementation should be better.
