### ISSUE TITLE
XMLStandardSubset + Subset-Version

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#19]
XMLStandardSubset is an enumeration of defined subsets but without any version number of the subset. The current EDASxChem/Bau subsets refer to EDASxChem/Bau version 2.2 based on SDScomXML version 4.0.3. With the release of SDScomXML 4.2.0, the version number has to be changed (e.g. to 2.3) without changing the selected fields. At the moment this is done implicitly but in future, we want to change the selected fields of the subset explicitly independently of the SDScomXML version (e.g. adding the field AdrTunnelRestrictionCode, discarding old classification). Therefore, EDASx version number is needed either in the enumeration of XMLStandardSubset or in a separate field is (e.g. XMLStandardSubsetVersionNo).

**Comment by dirk-qualisys** [comment]
IMHO, the EDASxBau/Chem (substandard) version number should always have a 1:1 relationship to an SDScom version number to avoid inconsitencies, i.e.
         EDASxBau/Chem 2.2 <-> SDScom 4.0.3
         EDASxBau/Chem 2.3 <-> SDScom 4.2.0
Thus, the field InformationFromExportingSystem/XmlStandardVersionNo is sufficient to identify the substandard version also. Introducing an additional field can lead to inconsistent information (e.g. EDASxBau/Chem 2.2 with SDScom 4.2.0). 

I think an additional field has more disadvantages than advantages, but I leave this open in case others do not agree with the 1:1 relationship assumption.

**Comment by QuenzelGISBAU** [comment]
I think Herr Henrich is making a valid point.  
Since changing the SDSComXML specifications is already bureaucratic process and is going to be more so in the future, it should be possible to redefine the subsets on short notice without having to change the main format version number.
It is true that this might lead to inconsistent information, of course.
But if I am not mistaken, as long as the subset version numbers are floats it is possible to restrict version numbers, e.g. EDASxBau/Chem >= 2.3 in SDSComXML 4.2.1.
I can see that this is not an easy topic, but nevertheless one that has to be not dismissed to easily.

**Comment by dirk-qualisys** [comment]
Jasper Quenzel, does your comment still hold true after the meeting in Berlin? Since there is a decision that EDASxBau/Chem can ask for a new SDScom release any time, it should always be possible to define a new SDScom release on short notice and then derive the EDASxBau/Chem version from the main version. If you agree, we should include this in the documentation and, for consitency concerns, drop the idea of a subset version field.
If anybody finds any scenario where the subset version field is necessary, we should certainly introduce it.

**Comment by QuenzelGISBAU** [comment]
In my opinion is this matter solved now. What does Mr Henrich think about this?

**Comment by QuenzelGISBAU** [comment]
Of course it should be "In my opinion this matter is solved now" . I was not trying to phrase a question :-P

**Comment by Henrich-BGRCI** [comment]
I think assigning a new version number to SDScom just for redefining a subset like EDASxChem/Bau is fine. The only consequence of this is that SDScom will have to different version numbers for exactly the same set of XSD (without any changes). For the EDASxChem/Bau version numbers, we should use the same numbering as for the corresponding SDScom.

**Comment by dirk-qualisys** [comment]
Example 1:
Date t: Release of SDScom 4.2.90
t+1: EDASxChem requires a change.
t+2: SDScom requires a change.
t+3: Regular release of SDScom 4.2.91 and EDASxChem 4.2.91

Example 2:
t+4: EDASxChem requires a change with immediate release
t+5: Release of SDScom 4.2.91.1 and EDASxChem 4.2.91.1
t+6: Regular release date of SDScom. Since there is no change, SDScom/EDASxChem release 4.2.92 is identical to 4.2.91.1. The release is still necessary for cooperation with the phrase catalogs.

Example 3:
t+7: SDScom requires a change.
t+8: Regular release of SDScom 4.2.93 and EDASxChem 4.2.93 (although the change soes not affect EDASxChem)

Do we all agree that the above scheme would work for all projects? Having different release numbers which are identical are indeed the biggest issue, but something that should be easy enough to deal with. If nobody disagrees until end of this month, I would like to close this and document the solution.

**Comment by dirk-qualisys** [comment]
Discussed (no objections) at the workshop in Hamburg, 19.Nov.2015
