### ISSUE TITLE
Additional fields for Switzerland

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#196]
CPID: The product registration number for Swiss FOPH. Part of section 15 of SDS
Störfallverordnung CH: Structure identic to Germany
VEVA: Swiss Waste code (values differ from EAK, structure is the same as EAK)

Is it possible to have this changes within version 4.4.0 (the intended long-term version)?

As I am not sure, where to publish the CH-xsd, I add the code here. Please assist and add it to source.
 
[SDSComXMLNE_CH.zip](https://github.com/esdscom/sdscom-xml/files/2658127/SDSComXMLNE_CH.zip)

**Comment by dirk-qualisys** [comment]
As Stoerfallverordnung has the same structure in Switzerland and Germany and dapts a European directive, I moved this to CT.XSD and renamed the field to Stoerfallverordnung (without CH), since the use for Switzerland's implementation is clear with the position in a national extension. Also adjusted the header to use namespaces, and integrated this in Github.

But most importantly: Many, many thanks for taking care of this! I hope it will work as an example for other countries!

**Comment by Suter-IK** [comment]
Good idea to move the structure into CT.xsd and leave the reference in the country specific file. And many thanks for your help doing this.
