### ISSUE TITLE
Python Example loading xsd schema and adding some content

### ISSUE THREAD

**Issue by FloHab** [esdscom/sdscom-xml#262]
Hi,

does anyone has some example code in python showing how to prepare a sdscom-xml and add some content to it?

Thanks in advance,

**Comment by dirk-qualisys** [comment]
I apologize that there was no quicker reply due to resource constraints.

You are basically asking for an implementation of eSDScom, which is beyond the complimentary support provided via GitHub issues. I will leave this open in case anybody wants to add a solution here or contact you directly, but there will be no such code example from the eSDScom workgroup. I am sorry to have no better news.
