### ISSUE TITLE
HazardStatementEnum 360D not found in 5.5

### ISSUE THREAD

**Issue by junma-dlyxt** [esdscom/sdscom-xml#270]
Has HazardStatementEnum 360D been removed from version 5.5?  360D is defined in sds xml 4.4, but I couldn't find it in version 5.5.  Thanks in advance.

**Comment by dirk-qualisys** [comment]
You are right, this was deleted when structuring the H phrases according to GHS revisions because these variants (all H360 and H361 with D, F, d, and/or f suffix) are not part of UN GHS. It seems this is an EU addition adopted by Australia too, but I did not look into all of the world's GHS implementations to see where it is used. At least China and South Africa do not use those suffixes, while USA and Canada do not refer to H phrase numbers at all.

We will reintroduce this as an EU extension. Thank you for the hint!
