### ISSUE TITLE
How to handle NULL or undetermined values?

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#33]
In case of physical and chemical properties: How and where should be the information placed?

1. "No data available / Keine Angaben vorhanden" (NULL value)
2. "cannot be determined / not applicable / nicht bestimmbar / nicht anwendbar / ..."

At the current release, the only possibility is to write the text in Comments or Methods (if the field is available). How should it be handled in the next releases?

**Comment by dirk-qualisys** [comment]
The requested info is similar to the info for non-classification in CLP notifications with EChA, i.e. I would expect all relevant waiving reasons. For physical or chemical properties, these are:
1. cannot be determined = technically impossible to obtain (pH value for solids, arguably)
2. not applicable = irrelevant (because no hazard assessment requires such info)
3. no data = unknown (not tested so far)

Should there be an additonal value for inconclusive data, i.e. in case of natural products with changing properties? I on't think so as test results could provide a range and should be conducted until a conclusive result is achieved.

**Comment by dirk-qualisys** [comment]
I would like to vote against putting such info in the "Method" tag, because methods should be limited to methods accepted under GHS or other relevant documents (like UN Manual of Tests and Criteria, http://www.unece.org/trans/danger/publi/manual/manual_e.html) for better processing.

Proposal: In PhysChemUnitValue, add an enum field "ReasonForWaiving" as an alternative to the sequence of UnitValue/Method/TestReference, but allow Comment anyway. Any other types affected?

**Comment by Henrich-BGRCI** [comment]
In addition to PhysChemUnitValue, the enum field "ReasonForWaiving" should be also added to all similiar datatypes: Value (e.g. in Solubility/Ph), UnitValue (e.g. in PhValue/Concentration), PhysChemValue (ExplosionLimit, ContentOfVoc), PhysChemUnitValueWithTemperature and PhysChemValueWithTemperature.

**Comment by dirk-qualisys** [comment]
IMHO, "ReasonForWaiving" should not be added to Value or UnitValue because it describes meta information. It belongs only in data types that contain such information (and usually include a Value or UnitValue).

I agree it should be added to PhysChemValue, PhysChemUnitValue, PhysChemValueWithTemperature, PhysChemUnitValueWithTemperature for consistency.

**Comment by nils-eska** [comment]
An enum field "ReasonForWaiving" should only be added to PhysChemUnitValue, PhysChemValueWithTemperature, PhysChemUnitValueWithTemperature.

**Comment by dirk-qualisys** [comment]
@Nils: Why not PhysChemValue? I am thinking that the determination of any phys/chem value -- with or without temperature, with or without unit -- could be waived for good reasons.

**Comment by nils-eska** [comment]
Sorry, my failure. I forgot to mention the PhysChemValue.

The PhysChemValue should also have the Field "ReasonForWaiving".
