### ISSUE TITLE
SDScom versioning when no changes occured

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#39]
The usual release schedule plans for a new version every six months, in sync with EuPhraC. What happens if no XML changes were necessary?

_Alternative 1:_ Release a new, but identical version of SDScom to demonstrate match to the newest EuPhraC.

_Alternative 2:_ No additional release. Clarify in the documentation that every SDScom release matches EuPhraC with the matching or any newer version number, unless a newer and matching SDScom release exists (is there any easier wording for this?).

Which is better?

**Comment by QuenzelGISBAU** [comment]
I think the second alternative is the better one. Especially since too frequent changes in the SDScomXML version numbering might discourage developers to implement SDScomXML.

**Comment by Henrich-BGRCI** [comment]
I also agree to the second alternative (No additional release number).

What should be the first SDScom version number with changes, after an EuPhraC release (e.g. 2.3) w/o changes in SDScom? Would it be e.g. 4.2.3.0 or 4.2.3.1? 
Here, I would prefer 4.2.3.1 for the release with SDScom changes, and blocking 4.2.3.0 just as an implicit numer due to the EuPhraC changes (but still using officially the former version number, e.g. 4.2.2.x).

**Comment by dirk-qualisys** [comment]
With (not much after) a EuPhraC release 2.3, there would be an SDScom release 4.2.3 (without a trailing .0 since a fourth number is only assigned for intermediate releases). A first intermediate release should be 4.2.3.1, i.e. we would never use .0 as the fourth number.

I think this is what you meant. Please correct me if there was a misunderstanding.

**Comment by Henrich-BGRCI** [comment]
Correct, this is what I wanted to say.
