### ISSUE TITLE
Complex types

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#40]
I don't get why there are a lot of elements of a complex type which is defined in SDSComXMLCT.xsd, while others are just described fully, without a special type definition, in SDSComXML.xsd.
For example the element "PhysicalChemicalProperties" has its own type and "IdentificationSubstPrep" has not.

**Comment by dirk-qualisys** [comment]
True - I also stumbled over this. If there are no objections, I would like to make this a thread for re-engeneering any such issues. This should be kept open for v4.

**Comment by dirk-qualisys** [comment]
My proposal: 

1. We should take the fields of type "Composition" and "Mixture" directly in SDSComXML, removing the separate type definitions for consistency's sake. The other types (i.e. Substance, ExposureControlPersonalProtection, PhysicalChemicalProperties, ToxicologicalInformation, EcologicalInformation) are used within the type "Component", so they are necessary as a separate definition.

2. Looking from the other way: Ecotoxicity, Species, GasGroup, PhysicalHazardsGeneralInformation, TemperatureClass, PhraseCatalogue which are currently defined in SDSComXMLDT should become part of SDSComXMLCT as they are complex types. Personally I prefer to leave Phrase and similar types (SignalWord etc.) in DT although technically complex because phrases are a base type for SDScom, but that certainly is a question of coding style.

**Comment by dirk-qualisys** [comment]
As the discussion wasn't too vivid, I applied the changes proposed above.
