### ISSUE TITLE
Voc Directive

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#46]
For 15.1.1.6 Voc, is it required to give next to the voc values (15.1.1.6.1 VocInPercentByWeight and 15.1.1.6.2 VocValue) also the directive in 15.1.1.6.3 VocRestrictionComments? Or, is it implicitly given that all voc values belong to the Directive 2004/42/EC?

The element Voc occures 0:n, other directives could be e.g. Directive 1999/13/EC ("the Paints Directive")  or the Industrial Emissions Directive 2010/75/EU.

**Comment by dlichtenberger-chemdox** [comment]
Actually the Voc element (15.1.1.6) is 0..1 in SDSComXML 4.2.0.

**Comment by dirk-qualisys** [comment]
We need to look at the real VOC content and the thresholds according to EU law separately. 

1. Section 15 (element "Voc") lists the real VOC content only, which is calculated based on the composition of a product. Any pure substance is either 100% VOC or 0% VOC to my understanding. Thus there is no need for more than one VOC value here (but this value is presented in wt.% and g/L).

2. Directive 2004/42/EC amends 1999/13/EC, thus both belong to the same legal act and there should be only values according to 2004/42/EC today, so that should be implicit. SDScom expects the respective content in HazardIdentification/HazardLabelling/LabellingAccordingToOtherEuLegislation/VocLabelling. I have clarified this in the annotation of VocLabelling. However, EuPhraC lists both directives separately - I have yet to clarify this with EuPhraC and thus keep this issue open.

3. Directive 2010/75/EU lists threshold for industrial plants not per substance, so I see no way to present helpful values in a substance-based document. EuPhraC lists this directive together with a VOC value that I think we have in "Voc" (see 1.) Again, I believe EuPhraC should change this and will follow up with them.

**Comment by dirk-qualisys** [comment]
Both EU directives have their own definition of VOC, Switzerland and some US states have others. I am currently working with EuPhraC to present a consistent structure for 4.2.2.

**Comment by dirk-qualisys** [comment]
I have added EuLegislation/IndustrialEmissions now. This takes care of the missing VOC value, but summarizes all other information related to directive 2010/75/EU in one field "OtherInformation". 

To be honest, I am not too confident that we have the best structure in place now, especially since there are still structural deviances with EuPhraC. As there will be better procedures in place to ensure consistency between both projects and this will bring up the issue again anyway, I will close this as the initial question is solved.
