### ISSUE TITLE
HandProtection

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#56]
Under 8.5.3 HandProtection (0:1), the child fields (here especially: SuitableMaterials, GloveBreakthroughTime, ThicknessOfGloveMaterial) can be occured n-times but they are not bundled. At the moment, it is not possible to do a coupling between these fields. Here, a bundling like for RecommendedRespiratoryProtectionArticles should be introduced to discribe suituations like this:

  SuitableMaterials=Nitrilkautschuk, GloveBreakthroughTime=240 min, ThicknessOfGloveMaterial=0.2 mm
 SuitableMaterials=Butylkautschuk, GloveBreakthroughTime=240 min, ThicknessOfGloveMaterial=0.3 mm
SuitableMaterials=Butylkautschuk, GloveBreakthroughTime=480 min, ThicknessOfGloveMaterial=0.7 mm

**Comment by dirk-qualisys** [comment]
I think you are right. This also applies to "WearDurationAtOccationalContact" (which should of course be renamed to "WearDurationAtOccasionalContact") and "WearDurationAtPermanentContact". All five fields should become part of "HandProtectionEquipment" if I don't misunderstand anything as they describe the same article.

To treat this as an enhancement, I suggest to add all to "HandProtectionEquipment" and currently keep the existing fields.

**Comment by dirk-qualisys** [comment]
Rethinking... let's not combine the vendor-independent info with ProtectionArticle. 

This is my state of knowledge: We need 
  * SkinHandProtectionShortTermContact
  * SkinHandProtectionLongTermContact
  * UnsuitableMaterials
  * HandProtectionNecessaryProperties (but what properties would exist that are not part of the other fields?)
  * AdditionalHandProtectionMeasures
  * ReferenceRelevantStandard
  * HandProtectionComments
as a general info, each field separately unbounded. The rest should IMHO be bundled, the bundle being unbounded and having unbounded "ProtectionArticle"s so that I can describe several glove types and deliver more than one article for each type. 
![unbenannt](https://cloud.githubusercontent.com/assets/4411785/12529860/68804592-c1c8-11e5-9676-99d745741639.JPG)
More complex than today certainly, but covers all that I can think of. Please comment.

**Comment by dirk-qualisys** [comment]
Accidentally added this already in commit 341baa6e8091f85c84a431f8b0b3f878789b2ba0 . So now it's available for testing, but we can certainly still change it if inappropriate.

**Comment by Henrich-BGRCI** [comment]
I think, these fields are exactly what we need to cover the example situation described above.
