### ISSUE TITLE
ClpHazardStatement minOccurs = "0"

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#59]
At the moment the min occurrence of ClpHazardStatement inside of ClpHazardClassification is one. This should be zero since the hazard classes "Expl. 1.6", "Org. Perox. G" and "Self-react. G" don't have an associated hazard statement.

**Comment by dirk-qualisys** [comment]
Not too urgent since this is not CLP, but valid point for UN GHS and the regions implementing this category. We should consider this in the context of scope enhancement. Of course the change would be easy, but I have set this to version 5.x for now because dropping the constraint imposes the risk of invalid data. Please comment if you disagree.

**Comment by QuenzelGISBAU** [comment]
I have checked this and it seems that this is indeed CLP and therefore needs to be corrected asap.

**Comment by nils-eska** [comment]
Yes, these hazard characteristics are part of CLP and we have to change this within the next release.

**Comment by dirk-qualisys** [comment]
I am sorry, my fault. Thus it's a bug. Please comment if this requires a maintenance release (4.2.1.2), otherwise it will go into 4.2.2 in April.
