### ISSUE TITLE
EDAS: Multiple Solubilities possible

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#63]
The element Solubilities (9.2.11) is unbounded in the XML schema but described as 0:1 in SDSComXmlStandard_EDASxChem-Bau-4.2.0.xls.

I'm not sure what multiple Solubilities container elements are intended for - the nested Solubility tag is already unbounded.

**Comment by dirk-qualisys** [comment]
My view is that Solubilities should be unbounded (as there could be solubility info in ethanol, in water, in fat...). The SolubilityDescription should be unbounded as it can be longer than one phrase. Solubility should be changed to 0..1 because Solubilities is unbounded already.

Clearly, having Solubilities as 0..1 and Solubility unbounded is an alternative that would work as well - it simply means that we have only one SolubilityDescription for all solubility info. 

Nils, any insight what was meant originally or makes more sense from you point of view?

**Comment by nils-eska** [comment]
The original idea was to have a separation of the different mediums and to have an own description for each medium if it is needed.
I know that this approach is quite fine granulated but we should keep solubilities unbounded.

**Comment by nils-eska** [comment]
This issue will be solved as follows:
The value of Solubility will be set to unbounded and the Solubility itself to 0..1. So it is possible to have more than one value related to the temperature for a specific medium.
