### ISSUE TITLE
RegulationsRelatedToCountryOrRegion: RegionCodes?

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#66]
Are there region codes available in the enumeration? Several customers create sds for country combinations: Germany-Austria-Switzerland / Belgium-Netherlands / Belgium-France / Ireland-UK / France-Switzerland / Italy-Switzerland. 
An other solution would be to attach 2 or more XML files to such a combined sds (one for each country)

**Comment by dirk-qualisys** [comment]
True, we experience the same - although the choice of regions is certainly limited by legal constrains (you cannot legally combine en-GB and en-US, and sometimes not even en-US and en-CA). But as long as we talk about European SDS, that is not relevant for SDScom.

Since the paradigm is that one SDScom "Datasheet" should match one SDS document, I suggest to define "RegulationsRelatedToCountryOrRegion" as unbounded.

**Comment by dirk-qualisys** [comment]
This approach may help to introduce a scope enhancement which was already meant to be part of version 5: As long as we stay within the boundaries of an EU safety data sheet, this enhancement can provide information for several countries (but in just one language, obviously).

As this has been open for two weeks, I will implement the change.
