### ISSUE TITLE
set HazardousWaste minOccurs=0

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#73]
Since the information, whether waste is hazardous or not, is communicated as part of the EWL number, this information is redundant. One should therefore not be forced to communicate it explicitly.

**Comment by dirk-qualisys** [comment]
Sounds reasonable to me because it is easy to distingush between "false" = non-hazardous waste, and an empty value = no information. If an EWL number (or List of Wastes code) and this value are both provided, this constitutes a redundancy which would unltimately require validation. So it should be ok to make this optional.

**Comment by dirk-qualisys** [comment]
Checked regulation 830/2015 and EChA's SDS guidance v3: no objections.
