### ISSUE TITLE
Unique country identification of Supplier

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#80]
A Supplier may have many roles with corresponding addresses. 

When we do import, the unique identification of a Supplier is the field: LegalRegistrationNo. I would like to see a new field that had the type CountryCodeEnum for uniquely pin the Supplier to a country.

The new field should be at the same level as LegalRegistrationNo.

**Comment by Suter-IK** [comment]
I see this as a "must have" because the intention was to allow more than one country code for "RegulationsRelatedToCountryOrRegionCode"

**Comment by dirk-qualisys** [comment]
The SupplierInfomation/Address has PostCountry and VisitingCountry for both address types. I do not really like the fact that these are free-form strings instead of ISO country codes, but doesn't that fulfil the requested country information for each supplier address? Since these are two fields that can have different content, they do not provide unambiguous information for the LegalRegistrationNumber however.

And the problem gets bigger: What is the country of CompanyContact? And what is CompanyContact/NationalContact meant for?

I would expect to have postal address, visiting address, company contact and legal registration number all in the same country, and would like to suggest we reorganize the whole section SupplierInformation so that we have one field Country with ISO code right after Role, and this should be valid for all fields in this section. Thus we can have one instance of SupplierInformation per combination of Role and Country. What do you think?

**Comment by dirk-qualisys** [comment]
If you agree to the above approach, a quick fix would be to add the field Country as suggested, but leave the rest as-is for v4.2.2. With the next refactoring release (4.3), we could then clean up the other parts.

**Comment by nils-eska** [comment]
To have the related country only at the level of the "SupplierInformation" is a good approach and to have at first the country field in 4.2.2 and the remove of all other Country Information in 4.3 should be fine.
