### ISSUE TITLE
Version numbering of components

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#83]
When receiving SDS the InternalSdsId will indicate the senders sds-id (identification of that particular SDS). 
When receiving new SDS in the same language, the receiver will assume that it is a new version of the same SDS. 
When receiving the same InternalSdsId in a new language, the receiver will assume it is the first version of the new language.

At first when receiving a mixture the sender will add a componentId as a attribute, all is good. When the sender is sender sends a new version the SDS. Should the receiver use the same component, or should the it always add a new version to the component?

It would be nice to have new field to indicate the version-number of the component used in a mixture.

**Comment by nils-eska** [comment]
From my point of view, the importing system have to check, whether the component is the same or not. If the properties of the component are different, a new component have to be introduced.

Nevertheless, it is possible to add a Version number to the component.

**Comment by dirk-qualisys** [comment]
Don't mix the InternalSdsId with version numbers. If you receive a SDS for the first time, you cannot assume it is version 1 in the sender's versioning system because the pproduct willl likely exist for a while already. Also, some companies maintain consistent version numbers across all languages, i.e. if they issue a new SDS language, the first available document may carry version no. 5.

While technically possible, the IT systems I know don't maintain version information for components in a way that makes sense for ingredients in mixtures. So I do not see how we could populate such a field to serve your purpose - we cannot make it mandatory as it is not required, and you would end up with empty fields. So what Nils described is the only way: Create the assignment of components to your internal data sets during first import, then use this for updates and compare if the components still match any new version of the document.

Sorry to have no better news, but there is simply no legal requirement that would make it likely to receive better info.

**Comment by dirk-qualisys** [comment]
The UFI which will be introduced in the near future will ease this problem as it provides an easy way to understand if the composition changed (or just the representation in the SDS, for example!). While there might be other, supplier specific reasons to apply a new UFI, receiving the same UFI means you have the same composition, without comparing ingredients.

Is this good enough to close this topic without XSD changes?
