### ISSUE TITLE
Component concentration should be moved to Mixture

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#84]
When receiving a component, I think it should be reusable.

Today the concentration is in the type Component. I think it belongs to the type Mixture. In that way the component becomes easier to reuse.

**Comment by nils-eska** [comment]
The concentration must be part of the component and the mixture contains 1 to n components. 
I am not sure what exactly you mean with reuse of a component?

**Comment by thegbom** [comment]
A pure substance with a given classification and a given "OccupationalExposureLimit" (and other properties if those are given) is a reusable component. It can be used in many mixtures.

If we have a mixture with 90% water, where the water component with a "ComponentId". Later when this component is used by the importer-company into new mixtures. It is reused. In the new mixture the concentration is less than 90%. 

This enhancement is not critical, more like nice to have.

**Comment by dirk-qualisys** [comment]
I stumbled over this when reviewing the harmonized CLP notification format which supports multi-level compositions. In that case a mixture is a recursive structure and it makes sense to maintain the concentration outside the substance info. We should treat this as an enhancement in this context.

**Comment by dirk-qualisys** [comment]
From today's workshop in Hamburg: Taking the concentration one level up would change the list of components to either two lists (concentrations and components), or an alternating list of concentration and components. Both are considered unnecessarily complex. Last option would be to add more hierarchy in Component so that the new (lower) level as the "reusable" component data. Participants argued that if one can extract the component from a complex XML document, he/she should be able to void the concentration. The group decided not to change the definition.
