### ISSUE TITLE
ClpHazardStatement has maxoccurs = 2, but should have maxoccurs = 3

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#90]
The classification category Acute Tox 1 can have H300, H310 and H330. Then maxoccurs should be 3 and not 2 as it is defined today. Alternatively users should use composite H-phrases. 

Please forgive me if I am wrong.

**Comment by dirk-qualisys** [comment]
maxoccurs is 2 in this case because of the classification as Aerosol category 1 or 2, which have H222 or H223 together with H229 (see CLP table 2.3.1). 

For Acute Toxicity, you perform three classifications (oral, dermal, inhalative) separately. If a substance or mixture classifies as Acute Tox 2 for both dermal and oral exposure, you communicate this as "Acute Tox. 2; H300" and "Acute Tox. 2; H310" in two instances. Thus the class Acute Toxicity can have up to three occurences with the same or different categories, each having just one H phrase.

This is hardly understandible from CLP directly, you just have separating lines in table 3.1.3 between the H phrases where Aerosols don't have them. Please look at annex I for examples, e.g. index number 613-201-00-9.
