### ISSUE TITLE
Hiding i section 3 for third parties

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#91]
If a exporter would like to tell the importer that the concentrations of each substance should not be visible if the data is presented as a SDS to a third party. What field should be used to hide data in section 3?

**Comment by dirk-qualisys** [comment]
Why would you want to hide concentrations, and on which legal basis would that be allowed? In the EU, presenting the concentration range is part of all SDS compliance checks - also because this is necessary to justify the mixture classification. REACH does not foresee a scenario where you can force your customer to restrict access to your SDS. So the only way I see is to choose concentration ranges widely and wisely.

Do you have a real-life case you can describe so that we understand your case better?
